version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "miniconda3-4.7"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

conda:
  environment: doc/environment.yml

sphinx:
  configuration: doc/source/conf.py