name: mda
channels:
  - conda-forge
  - defaults
dependencies:
  - freud=2.11.0
  - pip=22.1.2
  - pip:
    - matplotlib==3.5.3
    - numpy==1.23.3
    - pandas==1.4.4
    - scienceplots==1.0.9
    - taichi==1.1.2
